{{- if and .Values.microservicesDemo.enabled (eq .Values.microservicesDemo.sourceType "git") }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: microservices-demo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
spec:
  interval: {{ default "10m" .Values.flux.interval }}
  url: {{ .Values.microservicesDemo.git.repo }}
  ref:
    {{- include "validRef" .Values.microservicesDemo.git | nindent 4 }}
  {{- include "gitIgnore" . | nindent 2 }}
  {{- include "gitCredsExtended" (dict "name" "microservices-demo" "packageGitScope" .Values.microservicesDemo.git "rootScope" . "releaseName" .Release.Name) | nindent 2 }}
{{- end }}
