{{- if and .Values.microservicesDemo.enabled (include "imagePullSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
