{{- if .Values.microservicesDemo.enabled }}
{{- $domainName := default .Values.domain .Values.hostname }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: microservices-demo
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`boutique.{{ $domainName }}`)
      kind: Rule
      services:
        - name: frontend
          port: 80
  tls:
    secretName: microservices-demo-tls
{{- end }}
