{{- if .Values.gitlabRunner.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4 }}
{{- end }}
