{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/component: "monitoring"
    {{- include "commonLabels" . | nindent 4 }}
{{- end }}
