{{- if and .Values.k6Operator.enabled (include "imagePullSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: k6-operator-system
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
