{{- if .Values.k6Operator.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: k6-operator-system
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
{{- end }}
