{{- $fluxSettings := merge .Values.gitlab.flux .Values.flux -}}
{{- if .Values.gitlab.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    checksum/dorkomen-values: {{ include (print $.Template.BasePath "/gitlab/values.yaml") . | sha256sum }}
spec:
  releaseName: gitlab
  targetNamespace: gitlab
  chart:
    spec:
      {{- if eq .Values.gitlab.sourceType "git" }}
      chart: {{ .Values.gitlab.git.path }}
      sourceRef:
        kind: GitRepository
        name: gitlab
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.gitlab.helmRepo.chartName }}
      version: {{ .Values.gitlab.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.gitlab.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.gitlab.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.gitlab.helmRepo.cosignVerify (eq $repoType "oci")) }}
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.gitlab.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettings | nindent 2 }}

  {{- if .Values.gitlab.postRenderers }}
  postRenderers:
  {{ toYaml .Values.gitlab.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "overlays"

  {{- if .Values.eckOperator.enabled }}
  dependsOn:
    - name: eck-operator
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
