{{- if and .Values.gitlab.enabled (default true .Values.httpsRedirect) }}
{{- $domainName := default .Values.domain .Values.hostname }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gitlab.{{ $domainName }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-webservice-default
          port: 8181
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: registry
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`registry.{{ $domainName }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-registry
          port: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: minio
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`minio.{{ $domainName }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-minio-svc
          port: 9000
{{- end }}
