apiVersion: v2
name: dorkomen
description: A Helm chart for deploying a curated set of Kubernetes platform components using GitOps (FluxCD)
type: application
version: 0.2.10
appVersion: "0.2.10"
kubeVersion: ">=1.28.0-0"
keywords:
  - platform
  - gitops
  - flux
  - logging
  - cicd
maintainers:
  - name: Dorkomen
dependencies: []
