apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Harvester Overlay
# Harvester HCI cluster - requires Traefik + MetalLB for ingress
#
# Deploy with FluxCD:
#   path: ./overlays/harvester

resources:
  - ../../base

configMapGenerator:
  - name: dorkomen-values
    behavior: merge
    files:
      - values-patch.yaml

commonLabels:
  environment: harvester
