{{- if and .Values.opentelemetryOperator.enabled (include "imagePullSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: opentelemetry-operator-system
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
