{{- if and .Values.gitlab.enabled .Values.certManager.enabled }}
{{- $domainName := default .Values.domain .Values.hostname }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard-tls
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
spec:
  secretName: gitlab-wildcard-tls
  issuerRef:
    name: {{ .Values.clusterIssuer | default .Values.certManager.clusterIssuers.selfSignedCA.name }}
    kind: ClusterIssuer
  commonName: gitlab.{{ $domainName }}
  dnsNames:
    - gitlab.{{ $domainName }}
    - registry.{{ $domainName }}
    - minio.{{ $domainName }}
    - kas.{{ $domainName }}
{{- end }}
