{{- if and .Values.gitlab.enabled (default true .Values.httpsRedirect) }}
{{- $domainName := default .Values.domain .Values.hostname }}
{{- $gitlabDomain := .Values.gitlab.values.global.hosts.domain | default $domainName }}
---
# HTTP to HTTPS redirect for GitLab webservice
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gitlab.{{ $gitlabDomain }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-webservice-default
          port: 8181
---
# HTTP to HTTPS redirect for GitLab registry
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-registry-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`registry.{{ $gitlabDomain }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-registry
          port: 5000
---
# HTTP to HTTPS redirect for GitLab minio
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-minio-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`minio.{{ $gitlabDomain }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-minio-svc
          port: 9000
---
# HTTP to HTTPS redirect for GitLab KAS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-kas-http-redirect
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    {{- include "commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kas.{{ $gitlabDomain }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: gitlab
      services:
        - name: gitlab-kas
          port: 8150
{{- end }}
