{{- if and .Values.elasticStack.enabled .Values.elasticStack.kibana.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kibana-transport
  namespace: {{ .Values.elasticStack.namespace | default "elastic-stack" }}
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: "logging"
    {{- include "commonLabels" . | nindent 4 }}
spec:
  insecureSkipVerify: true
{{- end }}
