{{- if .Values.metallb.enabled }}
{{- if .Values.metallb.addressPool.addresses }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallb.addressPool.name | default "default-pool" }}
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
spec:
  addresses:
  {{- range .Values.metallb.addressPool.addresses }}
    - {{ . }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.metallb.addressPool.name | default "default-pool" }}-l2
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
spec:
  ipAddressPools:
    - {{ .Values.metallb.addressPool.name | default "default-pool" }}
{{- end }}
{{- end }}
