{{- if and .Values.argocd.enabled .Values.certManager.enabled }}
{{- $domainName := default .Values.domain .Values.hostname }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: {{ .Values.clusterIssuer | default .Values.certManager.clusterIssuers.selfSignedCA.name }}
    kind: ClusterIssuer
  commonName: argocd.{{ $domainName }}
  dnsNames:
    - argocd.{{ $domainName }}
{{- end }}
